# Generated by Django 4.0.4 on 2022-05-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashion',
            name='img',
            field=models.ImageField(default='dfddff', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
